### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-magento#238]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] customize_example - By @guewen - #255 
- [ ] magentoerpconnect - By @guewen - #255 
- [ ] magentoerpconnect_catalog
- [ ] magentoerpconnect_export_partner
- [ ] magentoerpconnect_options_active
- [ ] magentoerpconnect_order_comment
- [ ] magentoerpconnect_pricing
- [ ] server_env_magentoerpconnect

**Comment by webtekindo** [comment]
Hello,

I see here https://github.com/OCA/connector-magento/tree/10.0:

> Odoo Magento Connector (also known as MagentoERPconnect) is a bi-directional connector, 100% compatible with the last OpenERP 10.0 and latest Magento versions (1.x).

Is the connector already working for Odoo 10? Maybe can close the issue?

**Comment by webtekindo** [comment]
bump!

**Comment by pedrobaeza** [comment]
Please don't spam this issue that is for tracking the status, and as you can see, there's nothing migrated yet. I'm deleting all these comments.

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza Hello do you know if someone already started something ?

**Comment by pedrobaeza** [comment]
Nobody has expressed interest for now, but starting from 9.0 branch (which is now included in 9.0), it shouldn't be too difficult to migrate.

**Comment by passboltUser** [comment]
Not sure if you're asking this: https://github.com/OCA/connector-magento/issues/256 , so I asked it.

**Comment by jaredkipe** [comment]
I believe this can be closed now.

**Comment by voldedore** [comment]
Hello, is this module ready for Odoo10 and `connector` v10?
If not, which highest version can I use for connecting currently running Magento store with Odoo?

**Comment by flotho** [comment]
Hi,
@saxomanu and I are porting also the v10 to magento 2.0.
The effort is there : https://github.com/saxomanu/connector-magento/tree/10.0-components-magento2 how could it be referenced  in the upgrade process ?

regards
